# Generated by Django 4.1.6 on 2023-03-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_doctor_pdf_rename_email_register_remail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='address',
            new_name='daddress',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='email',
            new_name='demail',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='dname',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='phone',
            new_name='dphone',
        ),
    ]
